'use client';
import { useState } from 'react';
import { ArrowRight,ArrowUpRight,Plus,Link2,FileText,Pin,Mail,Phone,CalendarDays,LockKeyhole } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { currency,type Entry } from './data';
import { attentionRecords } from './workflow';
import { eventsFor,calendarWarnings,today,shiftDate } from './calendar';
import { alive,manualOrder,RecordActions,DropTarget,SectionSearch,Picker,type StudioProps } from './studio-ui';
import { ActivityFeed,type Activity } from './editor';
export const newEntry=(section:string,extra:Record<string,string|number>={}):Entry=>({id:crypto.randomUUID(),section,title:'',status:section==='content'?'Idea':section==='decision'?'Open':'Proposed',version:0,...extra});
export function PageTop({eyebrow,title,action,label}:{eyebrow:string;title:string;action?:()=>void;label?:string}){return <div className="studio-heading"><div><p className="eyebrow">TWH / {eyebrow}</p><h1>{title}</h1></div>{action&&<button className="button" onClick={action}><Plus size={15}/>{label||'Add'}</button>}</div>}
const dateText=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'});
export function Pulse({props,activity,go}:{props:StudioProps;activity:Activity[];go:(s:string)=>void}){
 const [range,setRange]=useState('This week'),[allAttention,setAllAttention]=useState(false);const now=today(),end=shiftDate(now,range==='Today'?0:range==='Tomorrow'?1:range==='This week'?7:14),start=range==='Tomorrow'?shiftDate(now,1):range==='Next week'?shiftDate(now,7):now;
 const next=eventsFor(props.records).filter(e=>e.record.accountInclude!=='no'&&e.date>=start&&e.date<=end&&!['Cancelled','Completed','Published','Done'].includes(e.status));const attention=attentionRecords(props.records).slice(0,allAttention?undefined:6),campaigns=props.records.filter(r=>r.section==='campaign'&&alive(r));const core=props.records.filter(r=>r.section==='content'&&r.track==='Core'&&alive(r));
 return <div className="pulse"><div className="pulse-intro"><div><p className="eyebrow">TWH / PULSE</p><h1>In motion.</h1><p>{new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',timeZone:'Asia/Kolkata'})} <span>Account lead · {props.accountLead||'Simran'}</span></p></div><button className="button" onClick={()=>go('Account Calendar')}><CalendarDays size={16}/>Account calendar</button></div>
 {props.records.some(r=>r.id==='brand-model'&&alive(r))&&<section className="pulse-now"><div><span className="eyebrow">NOW</span><h2>Retail ambition.<br/><em>Bespoke expertise.</em></h2><p>TWH’s next chapter holds both. Build demand for retail while keeping customisation and Tanya’s expertise visible.</p><button className="text-button" onClick={()=>go('Strategy')}>The direction <ArrowRight size={16}/></button></div><div className="pulse-split"><div><strong>65<span>%</span></strong><p>Retail</p></div><div><strong>35<span>%</span></strong><p>Experience centre</p></div><small>Trade relationships run across both.</small></div></section>}
 <div className="pulse-columns"><section className="pulse-next"><div className="section-head"><h2>Next up</h2><button className="text-button" onClick={()=>go('Account Calendar')}>All dates <ArrowUpRight size={16}/></button></div><Tabs value={range} onValueChange={setRange}><TabsList>{['Today','Tomorrow','This week','Next week'].map(v=><TabsTrigger key={v} value={v}>{v}</TabsTrigger>)}</TabsList></Tabs>{next.length?<div className="next-events">{next.map(e=><button key={e.id} onClick={()=>props.onOpen(e.record)}><time><b>{e.date.slice(-2)}</b>{new Date(e.date+'T12:00:00').toLocaleDateString('en-IN',{month:'short'})}</time><div><small>{e.date===now?'Today':e.date===shiftDate(now,1)?'Tomorrow':dateText(e.date)} · {e.label}</small><strong>{e.title}</strong><p>{e.owner||'Owner to assign'}{e.time?' · '+e.time+' IST':''}</p></div><ArrowUpRight size={17}/></button>)}</div>:<div className="quiet-editorial"><p>No dates set for {range.toLowerCase()}.</p><button className="text-button" onClick={()=>go('Account Calendar')}>Plan the next piece of work <ArrowRight size={15}/></button></div>}</section>
 <section className="pulse-attention"><span className="eyebrow">ATTENTION</span><h2>Unblock the next move.</h2>{attention.map(r=><button key={r.id} onClick={()=>props.onOpen(r)}><span className={r.status==='Blocked'?'status-dot blocked':'status-dot'}/><div><strong>{r.title}</strong><small>{r.owner||'Owner to assign'} · {r.status}</small></div><ArrowUpRight size={15}/></button>)}{calendarWarnings(props.records).map(w=><button key={w.id} onClick={()=>props.onOpen(w.record)}><span className="status-dot blocked"/><div><strong>{w.record.title}</strong><small>{w.message}</small></div><ArrowUpRight size={15}/></button>)}{!attention.length&&!calendarWarnings(props.records).length&&<p className="quiet-line">No open decisions or blockers.</p>}{attentionRecords(props.records).length>6&&<button className="text-button" onClick={()=>setAllAttention(v=>!v)}>{allAttention?'Show less':'See all open work'}</button>}{props.canEdit&&<button className="text-button" onClick={()=>props.onOpen(newEntry('task',{status:'To do',kind:'Action'}))}><Plus size={14}/>Add an action</button>}</section></div>
 <section className="pulse-movement"><div><p className="eyebrow">MOVEMENT</p><h2>The account, unfolding.</h2><div className="movement-numbers"><span><b>{core.filter(r=>r.status==='Published').length}</b> / {core.length} core pieces published</span><span><b>{campaigns.length}</b> campaigns in the workspace</span></div></div><ActivityFeed items={activity.slice(0,6)} records={props.records} onOpen={props.onOpen}/></section></div>
}
export function StrategyView({props}:{props:StudioProps}){
 const [tab,setTab]=useState('Direction'),[query,setQuery]=useState('');const items=props.records.filter(r=>r.section==='strategy'&&alive(r)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).sort(manualOrder);
 return <div className="strategy-page"><PageTop eyebrow="STRATEGY" title="A point of view. A way forward." action={props.canEdit?()=>props.onOpen(newEntry('strategy')):undefined} label="Add direction"/><div className="strategy-compass"><span>01 · AWARENESS</span><ArrowRight/><span>02 · CONSIDERATION</span><ArrowRight/><span>03 · CONVERSION</span><ArrowRight/><span>04 · COMMUNITY</span></div><div className="studio-filters"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="Direction">Direction</TabsTrigger><TabsTrigger value="Six-month roadmap">Six-month roadmap</TabsTrigger></TabsList></Tabs><SectionSearch value={query} onChange={setQuery} placeholder="Search strategy…"/></div>{tab==='Direction'?<div className="strategy-narrative">{items.map((r,i)=><DropTarget className="strategy-chapter" props={props} r={r} key={r.id}><div><span className="entry-number">{String(i+1).padStart(2,'0')}</span><small>{r.phase||r.topic||'Direction'}</small></div><div><div className="studio-section-label"><button className="entry-title" onClick={()=>props.onOpen(r)}>{r.title}</button><RecordActions r={r} props={props} items={items}/></div><p>{r.notes}</p>{r.gate&&<blockquote><span>READINESS</span>{r.gate}</blockquote>}{r.kpi&&<p className="strategy-measure"><b>What we measure</b> {r.kpi}</p>}{r.url&&<a className="text-button" href={String(r.url)} target="_blank" rel="noreferrer">Strategy source ↗</a>}</div></DropTarget>)}</div>:<><p className="quiet-line">Assign directions to months as launch timing is confirmed. No dates are assumed.</p><div className="six-months">{Array.from({length:6},(_,i)=>'Month '+(i+1)).map(m=><section key={m}><h3>{m}</h3>{items.filter(r=>r.month===m).map(r=><button onClick={()=>props.onOpen(r)} key={r.id}>{r.title}<small>{r.date||'Date to confirm'}</small></button>)}{props.canEdit&&<button className="text-button" onClick={()=>props.onOpen(newEntry('strategy',{month:m}))}><Plus size={14}/>Plan a milestone</button>}</section>)}</div>{items.some(r=>!r.month)&&<div className="unassigned-directions"><h3>Awaiting a month</h3>{items.filter(r=>!r.month).map(r=><button key={r.id} onClick={()=>props.onOpen(r)}>{r.title} <ArrowUpRight size={14}/></button>)}</div>}</>}
 </div>
}
export function CampaignView({props}:{props:StudioProps}){
 const [query,setQuery]=useState('');const stages=['Concept','Planning','In Production','Approval','Live','Completed'];const items=props.records.filter(r=>['campaign','launch'].includes(r.section)&&alive(r)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).sort(manualOrder);const statusFor=(r:Entry)=>stages.includes(r.status)?r.status:['Approved','Done','Delivered'].includes(r.status)?'Completed':r.status==='In progress'?'In Production':'Concept';
 return <><PageTop eyebrow="CAMPAIGNS & LAUNCHES" title="Ideas into the world." action={props.canEdit?()=>props.onOpen(newEntry('campaign',{status:'Concept'})):undefined} label="Create campaign"/><SectionSearch value={query} onChange={setQuery} placeholder="Search campaigns & launches…"/><div className="campaign-board">{stages.map(s=><section key={s} onDragOver={e=>props.canEdit&&e.preventDefault()} onDrop={e=>{e.preventDefault();const r=items.find(r=>r.id===e.dataTransfer.getData('application/x-twh-record'));if(r)void props.onSave({...r,status:s})}}><h3>{s}<span>{items.filter(r=>statusFor(r)===s).length}</span></h3>{items.filter(r=>statusFor(r)===s).map(r=><DropTarget key={r.id} r={r} props={props} className="campaign-card"><div className="studio-section-label"><small>{r.section==='launch'?'Launch workstream':'Campaign'}</small><RecordActions r={r} props={props} items={items}/></div><button className="entry-title" onClick={()=>props.onOpen(r)}>{r.title}</button><p>{r.objective||r.notes}</p><footer><span>{r.date?dateText(String(r.date)):'Date to confirm'}</span><span>{props.records.filter(x=>x.campaign===r.id&&alive(x)).length} connected items</span></footer></DropTarget>)}</section>)}</div></>
}
export function ScopeView({props}:{props:StudioProps}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('All services'),[cycle,setCycle]=useState(today().slice(0,7));const cycles=[...new Set([today().slice(0,7),...props.records.filter(r=>r.section==='content').flatMap(r=>[String(r.cycle||''),String(r.date||'').slice(0,7)]).filter(Boolean)])];const services=props.records.filter(r=>r.section==='service'&&alive(r)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase())&&(filter==='All services'||r.status===filter));
 return <><PageTop eyebrow="SCOPE" title="The work we’ve agreed to do." action={props.canEdit?()=>props.onOpen(newEntry('service')):undefined} label="Add service"/><div className="scope-intro"><p>One connected strategy. Clearly defined services.</p><span>Proposed terms stay labelled until approved.</span></div><div className="studio-filters"><SectionSearch value={query} onChange={setQuery} placeholder="Find a service…"/><Picker label="Delivery cycle" value={cycle} onChange={setCycle} options={cycles}/><Picker label="Service status" value={filter} onChange={setFilter} options={['All services',...new Set(services.map(r=>r.status))]}/></div><div className="service-ledger">{services.map(r=>{const connected=props.records.filter(x=>x.service===r.id&&alive(x)&&x.section===(r.deliverableType||'content')&&(r.frequency==='One-off'||x.cycle===cycle||String(x.date||'').startsWith(cycle))),delivered=connected.filter(x=>['Published','Delivered','Done','Completed'].includes(x.status)).length;return <DropTarget r={r} props={props} key={r.id} className="service-line"><div><span className="eyebrow">{r.category||r.frequency||'Service'} · {r.status}</span><button className="entry-title" onClick={()=>props.onOpen(r)}>{r.title}</button><p>{r.notes}</p>{r.excludes&&<small>Separate scope: {r.excludes}</small>}</div><div className="scope-delivery"><strong>{Number(r.quantity)>0?<>{delivered}<span> / {r.quantity}</span></>:connected.length||'—'}</strong><span>{Number(r.quantity)>0?'delivered · '+(r.frequency||'agreed cycle'):'connected items'}</span>{Number(r.quantity)>0&&<Progress value={Math.min(100,delivered/Number(r.quantity)*100)}/>}<button className="text-button" onClick={()=>props.onOpen(r)}>View scope <ArrowUpRight size={14}/></button></div><div className="scope-fee"><strong>{r.fee?currency(r.fee):'To quote'}</strong><small>{r.basis}</small><RecordActions r={r} props={props} items={services}/></div></DropTarget>})}</div></>
}
export function DirectoryView({props}:{props:StudioProps}){
 const [group,setGroup]=useState('All'),[query,setQuery]=useState('');const items=props.records.filter(r=>['team','vendor'].includes(r.section)&&alive(r)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase())&&(group==='All'||(r.section==='vendor'?'External':r.group||(/TWH|Tanya/.test(r.title)?'Client':'Agency'))===group)).sort(manualOrder);
 return <><PageTop eyebrow="TEAM & PARTNERS" title="The people behind the work." action={props.canEdit?()=>props.onOpen(newEntry(group==='External'?'vendor':'team',{group:group==='All'?'Agency':group})):undefined} label="Add person / partner"/><div className="studio-filters"><Tabs value={group} onValueChange={setGroup}><TabsList>{['All','Agency','Client','External'].map(g=><TabsTrigger value={g} key={g}>{g}</TabsTrigger>)}</TabsList></Tabs><SectionSearch value={query} onChange={setQuery} placeholder="Find people, roles or contacts…"/></div><div className="people-directory">{items.map(r=><DropTarget className="person-row" props={props} r={r} key={r.id}><div className="person-initials">{r.title.split(' ').slice(0,2).map(s=>s[0]).join('')}</div><div className="person-main"><button className="entry-title" onClick={()=>props.onOpen(r)}>{r.title}</button><span>{r.role||r.group||'Role to assign'}</span><p>{r.notes}</p></div><div className="person-contact">{r.email&&<a href={'mailto:'+r.email}><Mail size={14}/>{r.email}</a>}{r.phone&&<a href={'tel:'+r.phone}><Phone size={14}/>{r.phone}</a>}{r.location&&<small>{r.location}</small>}<span className="pill">{r.status}</span></div><RecordActions r={r} props={props} items={items}/></DropTarget>)}</div></>
}
export function LibraryView({props,section}:{props:StudioProps;section:'file'|'decision'|'report'|'private'}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[sort,setSort]=useState('Manual order');const all=props.records.filter(r=>r.section===section&&alive(r));const items=all.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())&&(category==='All'||String(section==='file'?r.folder||r.category:r.status)===category)).sort(sort==='Name'?(a,b)=>a.title.localeCompare(b.title):sort==='Recently updated'?(a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')):sort==='Date'?(a,b)=>String(a.date||'9999').localeCompare(String(b.date||'9999')):manualOrder).sort((a,b)=>section==='file'?Number(b.pinned==='yes')-Number(a.pinned==='yes'):0);
 const titles={file:'A place for every working document.',decision:'What we decided. And why.',report:'What changed. What comes next.',private:'Room to think.'};
 return <><PageTop eyebrow={section==='file'?'FILES':section.toUpperCase()} title={titles[section]} action={props.canEdit?()=>props.onOpen(newEntry(section)):undefined} label={'Add '+(section==='file'?'document':section==='private'?'note':section)}/>{section==='report'&&<div className="reporting-principle"><h2>Awareness → consideration → conversion</h2><p>Record verified reach, engagement, enquiries and attributable revenue. Connect each result to its source and next decision.</p></div>}{section==='private'&&<p className="quiet-line"><LockKeyhole size={15}/> These notes are visible only to you.</p>}<div className="studio-filters"><SectionSearch value={query} onChange={setQuery} placeholder={'Search '+section+'s…'}/><Picker label="Filter records" value={category} onChange={setCategory} options={['All',...new Set(all.map(r=>String(section==='file'?r.folder||r.category||'Unfiled':r.status)))]}/><Picker label="Sort records" value={sort} onChange={setSort} options={['Manual order','Recently updated','Name','Date']}/></div><div className={'library '+section+'-library'}>{items.map(r=><DropTarget r={r} props={props} key={r.id} className="library-row">{section==='file'?<FileText size={23}/>:<span className="ledger-date">{r.date?dateText(String(r.date)):r.status}</span>}<div className="library-copy"><div className="studio-section-label"><button className="entry-title" onClick={()=>props.onOpen(r)}>{r.pinned==='yes'&&<Pin size={14}/>} {r.title}</button><RecordActions r={r} props={props} items={items}/></div><p>{section==='decision'?r.outcome||r.notes:r.notes}</p>{section==='decision'&&r.outcome&&<small>Rationale: {r.notes}</small>}{section==='report'&&<div className="reported-metrics">{['reach','engagements','enquiries','sales','spend'].filter(k=>r[k]!==undefined&&r[k]!=='').map(k=><span key={k}><b>{Number(r[k]).toLocaleString('en-IN')}</b>{k}</span>)}</div>}<div className="library-meta"><span>{r.folder||r.category||r.owner||r.status}{r.versionLabel?' · '+r.versionLabel:''}</span>{r.url&&<a href={String(r.url)} target="_blank" rel="noreferrer">Open source <ArrowUpRight size={14}/></a>}</div></div></DropTarget>)}</div>{!items.length&&<p className="quiet-line">Nothing here yet. Add the first {section==='private'?'note':section} when it is ready.</p>}</>
}
export function InternalView({props}:{props:StudioProps}){
 const [tab,setTab]=useState('Commercials');const budget=props.records.find(r=>r.section==='budget'&&alive(r));const costs=budget?['design','subscriptions','people','overhead','contingency'].reduce((n,k)=>n+Number(budget[k]||0),0):0;
 return <><PageTop eyebrow="INTERNAL MANAGEMENT" title="Behind the account."/><Tabs value={tab} onValueChange={setTab}><TabsList>{['Commercials','Vendor costs','Private planning','Archive & trash'].map(t=><TabsTrigger key={t} value={t}>{t}</TabsTrigger>)}</TabsList></Tabs>{tab==='Private planning'?<LibraryView props={props} section="private"/>:tab==='Archive & trash'?<div className="archive-list">{props.records.filter(r=>['Archived','Deleted'].includes(r.status)).map(r=><div key={r.id}><div><strong>{r.title}</strong><small>{r.section} · {r.status}</small></div><button className="text-button" onClick={()=>void props.onSave({...r,status:String(r.previousStatus||'Proposed')})}>Restore</button></div>)}</div>:tab==='Commercials'?<div className="internal-budget">{budget&&<><section><span className="eyebrow">PROPOSED MONTHLY RETAINER</span><h2>{currency(budget.fee)}</h2>{['design','subscriptions','people','overhead','contingency'].map(k=><div className="budget-line" key={k}><span>{k==='people'?'Strategy, copy & account team':k[0].toUpperCase()+k.slice(1)}</span><strong>{budget[k]!==''&&budget[k]!==undefined?currency(budget[k]):'Not allocated'}</strong></div>)}<div className="budget-total"><span>Balance before unallocated costs</span><strong>{currency(Number(budget.fee)-costs)}</strong></div><p className="footnote">This balance is not profit. Account for strategy, copy, management time, overhead and contingency before treating it as margin.</p><button className="text-button" onClick={()=>props.onOpen(budget)}>Edit allocations <ArrowUpRight size={15}/></button></section><aside><h3>Commercial assumptions</h3><p>{budget.notes}</p><p>The 15 core pieces and the additional 15 trial reels have separate scopes. Production, specialist AI artists, ORM, performance, creators and website work remain separately costed.</p><a className="text-button" href="https://www.canva.com/design/DAHT15xjJiU" target="_blank" rel="noreferrer">Plutonik rate card ↗</a></aside></>}{!budget&&<button className="button" onClick={()=>props.onOpen(newEntry('budget'))}>Add account budget</button>}</div>:<div className="cost-ledger"><Table><TableHeader><TableRow><TableHead>Work / partner</TableHead><TableHead>Planned / quoted</TableHead><TableHead>Actual</TableHead><TableHead>Allocation</TableHead></TableRow></TableHeader><TableBody>{props.records.filter(r=>alive(r)&&(['vendor'].includes(r.section)||r.budget||r.actual)).map(r=><TableRow key={r.id}><TableCell><button className="table-title" onClick={()=>props.onOpen(r)}>{r.title}</button></TableCell><TableCell>{r.budget||r.fee?currency(r.budget||r.fee):'To quote'}</TableCell><TableCell>{r.actual?currency(r.actual):'Not logged'}</TableCell><TableCell>{props.records.find(x=>x.id===r.service)?.title||r.basis||'—'}</TableCell></TableRow>)}</TableBody></Table></div>}</>
}
