'use client';
import { useEffect,useState } from 'react';
import { Link2,Plus,Save,Upload,ExternalLink } from 'lucide-react';
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { toast } from 'sonner';
import { statuses,type Entry } from './data';
import { areas } from './workflow';
import { fieldsets,commonFields,fieldOptions,internalFields } from './fields';
import { Picker,MediaPreview,uploadFile,RecordActions,type StudioProps } from './studio-ui';
import { suggestedLabel,safeMediaUrl } from './media';
import type { CalendarState } from './operational-calendar';
import { eventsFor,calendarWarnings,dateLabels } from './calendar';
export type Activity={id:string;recordId:string;title:string;action:string;actor:string;at:string;fields:string[]};
export function ActivityFeed({items,onOpen,records}:{items:Activity[];onOpen:(r:Entry)=>void;records:Entry[]}){return <div className="activity-feed">{items.length?items.map(a=><button key={a.id} onClick={()=>{const r=records.find(r=>r.id===a.recordId);if(r)onOpen(r)}}><span className="activity-dot"/><div><strong>{a.title}</strong><p>{a.action} · {a.actor}</p><small>{new Date(a.at).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})}{a.fields?.length?' · '+a.fields.join(', '):''}</small></div></button>):<p className="quiet-line">Changes will appear here as the team works.</p>}</div>}
export function RecordEditor({entry,props,onClose,internal=false,calendar}:{entry:Entry;props:StudioProps;onClose:()=>void;internal?:boolean;calendar?:CalendarState}){
 const [d,setD]=useState({...entry}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[history,setHistory]=useState<Activity[]>([]),[comment,setComment]=useState('');
 const dirty=JSON.stringify(d)!==JSON.stringify(entry),editable=props.canEdit;
 useEffect(()=>{if(entry.version)fetch('/api/activity?record='+encodeURIComponent(entry.id)).then(r=>r.json() as Promise<{activity?:Activity[]}>).then(v=>setHistory(v.activity||[])).catch(()=>{});},[entry.id,entry.version]);
 function set(key:string,value:string){setD(x=>({...x,[key]:value}));}
 function close(){if(busy)return;if(dirty&&editable)setConfirm(true);else onClose();}
 async function save(){setBusy(true);setError('');try{const next:Entry={...d,title:d.title.trim()||suggestedLabel(String(d.assetUrl||d.url||''),String(d.notes||''),String(d.blockKind||d.category||'Untitled '+d.section))};delete next.editorPart;await props.onSave(next);onClose();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(file:File|undefined,key:string){if(!file)return;setBusy(true);try{const r=await uploadFile(file);props.onAccept(r);setD(x=>({...x,[key]:String(r.assetUrl),previewMime:String(r.mimeType||'')}));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function field([key,label,type]:[string,string,string?]){const rel=type?.startsWith('relation:')?type.slice(9):'',choices=type==='area'?areas:type?.startsWith('choice:')?type.slice(7).split('|'):fieldOptions[type||''];const value=String(d[key]??'');return <label className={'field '+(type==='textarea'?'wide':'')} key={key}><span>{label}</span>{rel?<Select value={value||'__none'} onValueChange={v=>set(key,v==='__none'?'':v)} disabled={!editable}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="__none">Not linked</SelectItem>{props.records.filter(r=>(rel==='any'||r.section===rel)&&r.id!==d.id&&!['Archived','Deleted'].includes(r.status)).map(r=><SelectItem key={r.id} value={r.id}>{r.title}</SelectItem>)}</SelectContent></Select>:choices?<Picker disabled={!editable} value={value||'Not set'} options={['Not set',...choices]} label={label} onChange={v=>editable&&set(key,v==='Not set'?'':v)}/>:type==='textarea'?<textarea disabled={!editable} rows={key==='script'?6:3} value={value} onChange={e=>set(key,e.target.value)}/>:<input aria-label={label} disabled={!editable} type={type==='url'?'text':type||'text'} min={type==='number'?0:undefined} value={value} onChange={e=>set(key,e.target.value)}/>}</label>}
 const allFields=(fieldsets[d.section]||[]).filter(f=>(internal||!internalFields.has(f[0]))&&(d.section!=='research'||!d.category||d.category==='Competitors'||!['offering','overview','tone','pillars','ads','works','gaps'].includes(f[0]))),primaryKeys=new Set(['notes','url','assetUrl','date','owner','category','blockKind','campaign','eventType','hook','script','caption','cta','insight','implication','quantity','fee','basis','role','email','phone','outcome','objective','idea','month','gate']);
 const primary=allFields.filter(f=>primaryKeys.has(f[0])),extra=allFields.filter(f=>!primaryKeys.has(f[0]));
 let palette:{name:string;hex:string}[]=[];try{palette=JSON.parse(String(d.palette||'[]'));}catch{}
 const related=props.records.filter(r=>r.id!==d.id&&r.status!=='Deleted'&&r.section!=='comment'&&(Object.values(d).includes(r.id)||Object.values(r).includes(d.id)));
 const comments=props.records.filter(r=>r.section==='comment'&&r.related===d.id&&r.status!=='Deleted');
 return <><Sheet open onOpenChange={v=>!v&&close()}><SheetContent className="editor"><SheetHeader><div className="editor-heading-actions"><p className="eyebrow">TWH / {d.section==='brandkit'?'VISUAL IDENTITY':d.section.toUpperCase()}</p>{!dirty&&entry.version>=0&&<RecordActions r={entry} props={{...props,onSave:async r=>{const saved=await props.onSave(r);onClose();return saved}}}/>}</div><SheetTitle>{d.title||'Add '+(d.section==='research'?'an observation':d.section==='brand'?'a brand chapter':d.section)}</SheetTitle><SheetDescription>{d.version?'Version '+d.version+' · '+(d.owner||'Owner to assign'):'Add the useful detail. You can complete the rest as the work develops.'}</SheetDescription></SheetHeader>
 <form className="editor-form" onSubmit={e=>{e.preventDefault();void save()}}>
 {d.section==='brandkit'?<>
 {(!d.editorPart||d.editorPart==='palette')&&<div className="wide palette-editor"><h3>Colour palette</h3>{palette.map((c,i)=><div className="palette-editor-row" key={i} draggable={editable} onDragStart={e=>e.dataTransfer.setData("application/x-twh-colour",String(i))} onDragOver={e=>editable&&e.preventDefault()} onDrop={e=>{e.preventDefault();const from=Number(e.dataTransfer.getData("application/x-twh-colour"));if(!Number.isInteger(from)||!palette[from])return;const next=[...palette],colour=next.splice(from,1)[0];next.splice(i,0,colour);set("palette",JSON.stringify(next));}}><input aria-label={'Colour '+(i+1)} type="color" value={c.hex} disabled={!editable} onChange={e=>set('palette',JSON.stringify(palette.map((v,j)=>i===j?{...v,hex:e.target.value}:v)))}/><input aria-label={'Colour name '+(i+1)} placeholder="Colour name" value={c.name} disabled={!editable} onChange={e=>set('palette',JSON.stringify(palette.map((v,j)=>i===j?{...v,name:e.target.value}:v)))}/><code>{c.hex}</code>{editable&&i>0&&<button type="button" aria-label={"Move colour "+(i+1)+" up"} className="text-button" onClick={()=>{const next=[...palette];[next[i-1],next[i]]=[next[i],next[i-1]];set("palette",JSON.stringify(next));}}>↑</button>}{editable&&<button type="button" className="text-button" onClick={()=>set('palette',JSON.stringify(palette.filter((_,j)=>j!==i)))}>Remove</button>}</div>)}{editable&&<button type="button" className="button" onClick={()=>set('palette',JSON.stringify([...palette,{name:'',hex:'#ffffff'}]))}><Plus size={14}/>Add colour</button>}</div>}
 {(!d.editorPart||d.editorPart==='type')&&['heading','body'].map(role=><div className="wide font-editor" key={role}>{field([role+'Font',role==='heading'?'Headline font name':'Body font name'])}{field([role+'FontUrl','Font file link','url'])}{editable&&<label className="text-button"><Upload size={14}/>Upload a licensed WOFF2 font<input type="file" accept=".woff2" hidden onChange={e=>void upload(e.target.files?.[0],role+'FontUrl')}/></label>}</div>)}
 </>:<><label className="field wide"><span>{['brand','research','asset','private'].includes(d.section)?'Name / label (optional)':'Name'}</span><input disabled={!editable} value={d.title} maxLength={200} onChange={e=>set('title',e.target.value)} placeholder={['research','private'].includes(d.section)?'Or start with the note below…':'Give the work a recognisable name'}/></label>{field(['status','Status','choice:'+statuses.join('|')])}{primary.map(field)}
 {extra.length>0&&<details className="editor-details wide"><summary>More detail & connections <span>{extra.length} fields</span></summary><div className="editor-extra">{extra.map(field)}</div></details>}
 {editable&&['brand','research','asset','file'].includes(d.section)&&<label className="text-button wide"><Upload size={15}/>Attach an image, video or PDF<input type="file" accept="image/png,image/jpeg,image/webp,image/gif,video/mp4,video/webm,application/pdf" hidden onChange={e=>void upload(e.target.files?.[0],d.section==='file'?'url':'assetUrl')}/></label>}
 {(d.assetUrl||d.section==='file'&&d.url)&&<div className="wide"><MediaPreview url={d.assetUrl||d.url} mime={String(d.previewMime||d.mimeType||'')} label={d.title}/></div>}
 <details className="editor-details wide"><summary>Tags, sharing & source</summary><div className="editor-extra">{commonFields.filter(f=>f[0]!=='source'||!allFields.some(x=>x[0]==='source')).map(field)}</div></details>
 </>}
 {calendarWarnings([...props.records.filter(r=>r.id!==d.id),d]).filter(w=>w.record.id===d.id).map(w=><p className="date-warning wide" key={w.id}>{w.message}</p>)}{eventsFor([d]).length>0&&<details className="editor-details wide"><summary>Google Calendar <span>{d.calendarSync==='yes'?'Sync requested':'Not synced'}</span></summary><div className="editor-extra"><label className="checkbox-line wide"><Checkbox checked={d.calendarSync==='yes'} disabled={!editable} onCheckedChange={v=>set('calendarSync',v?'yes':'no')}/>Connect these dates to the account lead’s calendar</label>{field(['calendarMode','Date source','choice:workspace|google|two-way'])}<p className="footnote wide">{calendar?.connected?"Connected to the account lead’s Google Calendar.":"Google authorisation is required. Dates stay editable here and retain their history."}</p>{calendar?.links.filter(l=>l.record_id===d.id).map(l=><div className="calendar-link-status wide" key={l.id}><span>{dateLabels[l.date_field]||l.date_field} · {l.status}</span>{l.external_url&&<a href={l.external_url} target="_blank" rel="noreferrer">Open in Google Calendar <ExternalLink size={13}/></a>}{l.error&&<small>{l.error}</small>}</div>)}{Object.entries(dateLabels).filter(([k])=>d[k]).map(([k,label])=><label className="checkbox-line" key={k}><Checkbox disabled={!editable} checked={!d.calendarFields||String(d.calendarFields).split(',').includes(k)} onCheckedChange={checked=>{const fields=d.calendarFields?String(d.calendarFields).split(','):eventsFor([d]).map(e=>e.field);set('calendarFields',checked?[...new Set([...fields,k])].join(','):fields.filter(f=>f!==k).join(',')||'none');}}/>{label} · {d[k]}</label>)}</div></details>}
 {related.length>0&&<div className="wide linked-records"><h3>Connected work</h3>{related.map(r=><button className="text-button" type="button" key={r.id} disabled={dirty} onClick={()=>props.onOpen(r)}><Link2 size={14}/>{r.title}<small>{r.section}</small></button>)}{dirty&&<small>Save this draft to open connected work.</small>}</div>}
 {error&&<p className="error-note wide" role="alert">{error}</p>}<div className="editor-actions wide"><button className="button" type="button" disabled={busy} onClick={close}>Close</button>{editable&&<button className="button primary" type="submit" disabled={busy}><Save size={15}/>{busy?'Saving…':'Save changes'}</button>}</div>
 </form>{d.version>0&&<div className="record-memory"><h3>Conversation & feedback</h3>{comments.map(c=><article key={c.id}><p>{c.notes}</p><small>{c.owner} · {c.createdAt?new Date(String(c.createdAt)).toLocaleDateString('en-IN'):''}</small></article>)}{<form onSubmit={async e=>{e.preventDefault();if(!comment.trim())return;try{const res=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:d.id,notes:comment})});const result=await res.json() as {record:Entry;error?:string};if(!res.ok)throw new Error(result.error);props.onAccept(result.record);setComment('')}catch(e){toast.error((e as Error).message)}}}><textarea aria-label="Add feedback" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add feedback or a decision note…"/><button className="text-button" disabled={!comment.trim()}>Add feedback <Plus size={14}/></button></form>}{!editable&&['Client review','Awaiting approval','Changes requested'].includes(entry.status)&&<div className="studio-actions">{['Approved','Changes requested'].map(decision=><button className="button" key={decision} onClick={async()=>{try{const res=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:d.id,decision,version:d.version})});const result=await res.json() as {record:Entry;error?:string};if(!res.ok)throw new Error(result.error);props.onAccept(result.record);onClose();toast.success('Response saved')}catch(e){toast.error((e as Error).message)}}}>{decision==='Approved'?'Approve':'Request changes'}</button>)}</div>}<h3>Activity</h3><ActivityFeed items={history} records={props.records} onOpen={()=>{}}/></div>}
 </SheetContent></Sheet><AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Keep your changes?</AlertDialogTitle><AlertDialogDescription>You have an unsaved draft.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep editing</AlertDialogCancel><AlertDialogAction onClick={onClose}>Discard draft</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
