export const fieldsets:Record<string,[string,string,string?][]>={
brand:[['lane','Business line','lane'],['notes','Positioning / working brief','textarea'],['source','Source / decision basis'],['url','Supporting document','url']],
research:[['url','Official brand / source link','url'],['offering','Offering','textarea'],['overview','Overview','textarea'],['tone','Tonality','textarea'],['pillars','Content pillars','textarea'],['ads','Observed ad strategy','textarea'],['works','What works','textarea'],['gaps','What does not work / opportunity','textarea'],['notes','Evidence, dates & implications for TWH','textarea']],
strategy:[['topic','Strategy topic','topic'],['phase','Growth phase','phase'],['date','Target date','date'],['owner','Accountable owner'],['notes','Strategic direction','textarea'],['gate','Readiness conditions','textarea'],['kpi','Success measures','textarea'],['service','Related service','relation:service'],['url','Strategy deck','url']],
task:[['area','Workstream','area'],['kind','Item type','kind'],['owner','Accountable owner'],['date','Due date','date'],['priority','Priority','priority'],['notes','Requirement / next action','textarea'],['url','Supporting link','url']],
content:[['track','Scope','track'],['cycle','Planning cycle'],['lane','Business line','lane'],['phase','Funnel / growth phase','phase'],['format','Format'],['channel','Publishing channels'],['date','Publishing date','date'],['deadline','Internal due date','date'],['owner','Assigned owner'],['approver','Client approver / approval note'],['hook','Opening hook','textarea'],['notes','Concept & creative direction','textarea'],['script','Script / talking-point skeleton','textarea'],['caption','Caption & copy','textarea'],['cta','Call to action'],['hypothesis','Trial hypothesis / learning objective','textarea'],['referenceUrl','Creative reference','url'],['assetUrl','Working asset / Drive folder','url'],['liveUrl','Live post URL','url'],['parent','Source content','relation:content'],['production','Production plan','relation:production'],['vendor','Vendor','relation:vendor'],['service','Cost allocated to','relation:service'],['budget','Planned asset cost (₹)','number'],['actual','Actual asset cost (₹)','number'],['results','Results & learning','textarea']],
production:[['owner','Production lead'],['date','Shoot / handover date','date'],['lane','Business line','lane'],['notes','Creative direction & production brief','textarea'],['shotlist','Shot list & run of show','textarea'],['assets','Equipment, props & asset allocation','textarea'],['deliverables','Handover deliverables','textarea'],['vendor','Assigned vendor','relation:vendor'],['service','Related service','relation:service'],['budget','Planned budget (₹)','number'],['actual','Actual cost (₹)','number'],['url','Master deck / Drive link','url']],
team:[['role','Role'],['email','Email','email'],['phone','Phone'],['capacity','Availability / capacity'],['notes','Responsibility & allocation','textarea']],
vendor:[['role','Specialism'],['contact','Contact person'],['email','Email','email'],['phone','Phone'],['location','Location'],['fee','Quoted fee (₹)','number'],['basis','Fee basis / inclusions'],['date','Availability date','date'],['url','Portfolio / quotation','url'],['notes','Capabilities, exclusions & payment notes','textarea']],
service:[['fee','Client fee / starting fee (₹)','number'],['basis','Commercial basis'],['owner','Service owner'],['notes','Included deliverables','textarea'],['excludes','Exclusions','textarea'],['reference','Rate-card reference / comparison','textarea'],['url','Approved scope / estimate','url']],
budget:[['fee','Monthly client fee (₹)','number'],['design','Design & editing allowance (₹)','number'],['subscriptions','Subscription allocation (₹)','number'],['people','Strategy, copy & account team cost (₹)','number'],['overhead','Overhead allocation (₹)','number'],['contingency','Contingency (₹)','number'],['notes','Assumptions','textarea']],
file:[['category','Document category'],['url','Canva / Drive / resource link','url'],['owner','Document owner'],['notes','Context & version notes','textarea']],
decision:[['area','Workstream','area'],['relatedTask','Related action','relation:task'],['outcome','Outcome / choice made','textarea'],['date','Decision / follow-up date','date'],['owner','Decision owner'],['source','Source / meeting'],['notes','Decision, rationale & impact','textarea'],['url','Supporting reference','url']],
launch:[['owner','Launch lead'],['date','Target milestone date','date'],['stage','Roadmap stage','stage'],['notes','Launch plan','textarea'],['gate','Readiness / go-live conditions','textarea'],['strategy','Related strategy','relation:strategy'],['production','Production plan','relation:production'],['url','Launch plan / working deck','url']],
asset:[['format','Asset type / format'],['lane','Business line','lane'],['owner','Asset owner'],['date','Delivery / review date','date'],['content','Source content brief','relation:content'],['production','Production plan','relation:production'],['assetUrl','Working file / final export','url'],['referenceUrl','Approval record','url'],['notes','Version, usage rights & handover notes','textarea']],
private:[['area','Related workstream','area'],['date','Follow-up date','date'],['notes','Private thinking / notes','textarea'],['url','Supporting link','url']],
report:[['cycle','Reporting period'],['date','Review date','date'],['owner','Report owner'],['reach','Reach','number'],['engagements','Engagements','number'],['enquiries','Qualified enquiries','number'],['sales','Attributable revenue (₹)','number'],['spend','Media spend (₹)','number'],['notes','Results, source & attribution limits','textarea'],['wins','What worked','textarea'],['next','What changes next month','textarea'],['url','Source report / analytics','url']]
};
const extend=(section:string,fields:[string,string,string?][])=>{const keys=new Set(fields.map(f=>f[0]));fieldsets[section]=[...(fieldsets[section]||[]).filter(f=>!keys.has(f[0])),...fields]};
extend('brand',[['blockKind','Block type','choice:Brand story|Founder words|Mission & vision|Positioning|Audience|Voice & tone|Vocabulary|Do & don’t|Photography|Art direction|Video direction|Gallery'],['assetUrl','Image / video / PDF link','url']]);
extend('research',[['category','Research lens','choice:Market|Audience|Competitors|Trends|Reference bank'],['evidence','Evidence level','choice:Question|Hypothesis|Client brief|Observed|Verified'],['lane','Audience','lane'],['notes','Observation','textarea'],['insight','Interpretation','textarea'],['implication','Implication for TWH','textarea'],['date','Observation date','date'],['assetUrl','Media link','url']]);
extend('production',[['eventType','Production activity','choice:Shoot|Preparation|Editing|Review|Revision|Delivery|Vendor booking'],['campaign','Campaign','relation:campaign'],['objective','Shoot objective','textarea'],['location','Location'],['talent','Talent'],['photographer','Photographer'],['videographer','Videographer'],['stylist','Stylist'],['producer','Producer'],['callSheetUrl','Call sheet','url'],['internalNotes','Private production notes','textarea'],['callSheetDate','Call-sheet date','date'],['bookingDate','Location / vendor booking date','date'],['prepDate','Preparation date','date'],['editDate','Editing date','date'],['reviewDate','Review date','date'],['revisionDate','Revision date','date'],['deliveryDate','Final delivery date','date']]);
extend('content',[['campaign','Campaign','relation:campaign'],['reviewDate','Review date','date'],['approvalDate','Approval date','date'],['time','Publishing time (IST)','time'],['pillar','Content pillar'],['bucket','Content bucket'],['dependsOn','Depends on','relation:production']]);
extend('asset',[['campaign','Campaign','relation:campaign'],['collection','Collection'],['versionLabel','Version label'],['previousVersion','Previous version','relation:asset'],['rights','Usage rights / expiry'],['feedback','Feedback','textarea']]);
fieldsets.campaign=[['objective','Objective','textarea'],['audience','Audience','textarea'],['idea','The idea','textarea'],['channel','Channels'],['owner','Campaign lead'],['startDate','Start date','date'],['date','Launch date','date'],['reviewDate','Review date','date'],['deadline','Deadline','date'],['deliverables','Deliverables','textarea'],['budget','Internal budget (₹)','number'],['approval','Approval / decision','textarea'],['results','Results','textarea'],['notes','Campaign brief','textarea'],['url','Working deck','url']];
fieldsets.event=[['eventType','Event type','choice:Client meeting|Presentation|Approval|Strategy workshop|Milestone|Vendor briefing|Deadline'],['date','Date','date'],['time','Time (IST)','time'],['owner','Owner'],['location','Location'],['campaign','Campaign','relation:campaign'],['production','Production','relation:production'],['content','Content','relation:content'],['vendor','Vendor','relation:vendor'],['notes','Agenda / context','textarea'],['url','Related files','url']];
extend('strategy',[['objective','Objective','textarea'],['audience','Audience','textarea'],['channel','Channels'],['month','Roadmap month','choice:Month 1|Month 2|Month 3|Month 4|Month 5|Month 6'],['campaign','Campaign','relation:campaign'],['reviewDate','Review date','date']]);
extend('service',[['quantity','Deliverable quantity','number'],['deliverableType','Count delivery from','choice:content|asset|production|task'],['frequency','Delivery cycle','choice:Monthly|Quarterly|One-off|Custom'],['category','Service model','choice:Core retainer|Optional add-on|One-off project|Custom mix'],['startDate','Service start','date'],['renewalDate','Renewal','date']]);
extend('decision',[['options','Options considered','textarea'],['impact','Impact on the account','textarea'],['campaign','Campaign','relation:campaign'],['supersedes','Supersedes','relation:decision']]);
extend('file',[['folder','Folder'],['versionLabel','Version label'],['pinned','Pinned','choice:yes|no'],['previousVersion','Previous version','relation:file']]);
extend('team',[['group','Network','choice:Agency|Client|External'],['areas','Assigned workstreams'],['reportingTo','Reports to']]);
fieldsets.comment=[['related','Related item'],['notes','Comment','textarea']];
export const commonFields:[string,string,string?][]=[['tags','Tags (comma-separated)'],['visibility','Who can see this','choice:agency|client'],['source','Source / provenance'],['calendarInclude','Include dated work in calendars','choice:yes|no'],['accountInclude','Include in account calendar and Pulse','choice:yes|no']];
export const internalFields=new Set(['budget','actual','capacity','people','overhead','contingency','subscriptions','design','internalNotes']);
export const fieldOptions:Record<string,string[]>={kind:['Input','Action','Decision'],topic:['Positioning','Audience','Messaging','Opportunities'],stage:['Now','Next','Later'],lane:['Retail','Bespoke','Trade','Both'],phase:['Foundation','Awareness','Amplification','Conversion','Community','Launch'],priority:['High','Medium','Low'],track:['Core','Trial']};

fieldsets.script=[['campaign','Campaign','relation:campaign'],['content','Content item','relation:content'],['production','Production','relation:production'],['owner','Owner'],['writer','Writer'],['channel','Platform'],['format','Format'],['objective','Objective','textarea'],['audience','Audience'],['territory','Creative territory'],['concept','Concept','textarea'],['hook','Hook','textarea'],['script','Script body','textarea'],['dialogue','Dialogue','textarea'],['voiceover','Voiceover','textarea'],['onScreen','On-screen text','textarea'],['visuals','Visual direction','textarea'],['shots','Shot direction','textarea'],['cta','Call to action'],['duration','Duration'],['shootDate','Shoot date','date'],['publishDate','Publish date','date'],['asset','Related asset','relation:asset'],['brief','Brief','relation:file'],['sourceRecord','Source document / meeting','relation:source']];
fieldsets.meeting=[['date','Meeting date','date'],['time','Time (IST)','time'],['participants','Participants'],['owner','Account lead'],['notes','Summary','textarea'],['decisions','Decisions','textarea'],['approvals','Explicit approvals','textarea'],['actions','Actions, owners and deadlines','textarea'],['unresolved','Unresolved questions','textarea'],['campaign','Campaign','relation:campaign'],['sourceRecord','Source document','relation:source'],['url','Minutes document','url']];
fieldsets.source=[['owner','Uploaded by'],['pageContext','Uploaded from'],['brief','Reading brief','textarea'],['notes','Source text / extracted account memory','textarea'],['summary','Summary','textarea'],['url','Source file','url'],['related','Related record','relation:any']];
fieldsets.communication=[['recipient','Recipient'],['channel','Channel'],['notes','Draft','textarea'],['related','Related record','relation:any']];
extend('campaign',[['strategy','Strategy','relation:strategy']]);
extend('content',[['scriptRecord','Script','relation:script']]);
extend('production',[['content','Content','relation:content'],['scriptRecord','Script','relation:script']]);
extend('decision',[['strategy','Strategy','relation:strategy'],['sourceRecord','Source / meeting','relation:any']]);
extend('file',[['related','Related record','relation:any']]);
extend('service',[['campaign','Campaign','relation:campaign']]);
