'use client';
import { useRef,useState } from 'react';
import { Plus,Upload,ArrowUpRight,ExternalLink,Palette,Type,Image as ImageIcon,Link2,BookOpen,ArrowRight } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { toast } from 'sonner';
import type { Entry } from './data';
import { researchCategories,researchCategory,safeMediaUrl,uploadPath } from './media';
import { type StudioProps,alive,manualOrder,RecordActions,DropTarget,MediaPreview,SectionSearch,Picker,uploadFile } from './studio-ui';
const fresh=(section:string,extra:Record<string,string|number>={}):Entry=>({id:crypto.randomUUID(),section,title:'',status:'Proposed',version:0,...extra});
const kitEmpty:Entry={id:'brandkit-twh',section:'brandkit',title:'TWH visual identity',version:0,status:'Awaiting input',palette:'[]'};
export function BrandStudio(props:StudioProps){
 const {records,onOpen,onSave,onAccept,canEdit}=props,kit=records.find(r=>r.id==='brandkit-twh')||kitEmpty;
 const blocks=records.filter(r=>r.section==='brand'&&alive(r)).sort(manualOrder),[busy,setBusy]=useState(false),input=useRef<HTMLInputElement>(null);
 let colors:{name:string;hex:string}[]=[];try{colors=JSON.parse(String(kit.palette||'[]'))}catch{}
 const fontCss=['heading','body'].map(role=>uploadPath.test(String(kit[role+'FontUrl']||''))?`@font-face{font-family:twh-${role};src:url("${kit[role+'FontUrl']}") format("woff2");font-display:swap}`:'').join('');
 async function logo(file?:File){if(!file)return;setBusy(true);try{const r=await uploadFile(file);onAccept(r);await onSave({...kit,logoUrl:r.assetUrl});toast.success('Logo added to the brand book')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <div className="brand-studio"><style>{fontCss}</style><div className="studio-heading"><div><p className="eyebrow">TWH / BRAND GUIDELINES</p><h1>The brand, in full view.</h1></div>{canEdit&&<button className="button" onClick={()=>onOpen(fresh('brand',{blockKind:'Brand story'}))}><Plus size={15}/>Add a block</button>}</div>
 <section className="brand-cover"><div className="brand-cover-copy"><span className="eyebrow">ONE BRAND. TWO WAYS TO BUY.</span><div className="brand-monogram">TWH<span>Retail ambition.<br/>Bespoke expertise.</span></div><p>65% retail focus. 35% bespoke experience.</p><small>Working account context · <a href="https://www.canva.com/design/DAHVQvUTAx4" target="_blank" rel="noreferrer">TWH discovery deck ↗</a></small></div><div className="brand-mark">{kit.logoUrl?<img src={String(kit.logoUrl)} alt="TWH brand mark"/>:<><ImageIcon size={32}/><p>The TWH mark belongs here.</p></>}{canEdit&&<><input ref={input} type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden onChange={e=>{void logo(e.target.files?.[0]);e.target.value=''}}/><button className="text-button" disabled={busy} onClick={()=>input.current?.click()}><Upload size={14}/>{busy?'Uploading…':kit.logoUrl?'Replace logo':'Add logo'}</button>{kit.logoUrl&&<button className="subtle-button" onClick={()=>void onSave({...kit,logoUrl:''})}>Remove from guidelines</button>}</>}<span className="brand-mark-caption">LOGO SYSTEM</span></div></section>
 <div className="identity-board"><section className="palette-board"><div className="studio-section-label"><span><Palette size={16}/> Colour system</span>{canEdit&&<button className="text-button" onClick={()=>onOpen({...kit,editorPart:'palette'})}>{colors.length?'Edit palette':'Add colours'} <Plus size={14}/></button>}</div>{colors.length?<div className="swatches">{colors.map((c,i)=><button key={i} className="swatch" onClick={()=>canEdit&&onOpen({...kit,editorPart:'palette'})} style={{background:c.hex,color:parseInt(c.hex.slice(1),16)>0x888888?'#111':'#fff'}}><span>{c.name||'Colour '+(i+1)}</span><code>{c.hex.toUpperCase()}</code></button>)}</div>:<button className="palette-empty" onClick={()=>canEdit&&onOpen({...kit,editorPart:'palette'})}><span>+　+　+</span>Add TWH’s approved palette.</button>}<small>Approved colours stay separate from Plutonik’s workspace colours.</small></section>
 <section className="type-board"><div className="studio-section-label"><span><Type size={16}/> Typography</span>{canEdit&&<button className="text-button" onClick={()=>onOpen({...kit,editorPart:'type'})}>Edit type <ArrowUpRight size={14}/></button>}</div><div className="type-specimens">{['heading','body'].map(role=><button key={role} onClick={()=>canEdit&&onOpen({...kit,editorPart:'type'})}><span className="type-example" style={{fontFamily:kit[role+'FontUrl']?'twh-'+role:role==='heading'?'Georgia,serif':'Arial,sans-serif'}}>Aa</span><strong>{kit[role+'Font']||'Choose '+(role==='heading'?'headline':'body')+' type'}</strong><small>{role==='heading'?'HEADLINES':'BODY & CAPTIONS'}{!kit[role+'Font']?' · Not supplied':''}</small></button>)}</div></section></div>
 <div className="brand-chapters">{blocks.map((r,i)=><DropTarget key={r.id} r={r} props={props} className={'brand-chapter '+(r.blockKind==='Founder words'?'quote-chapter':'')}><div className="chapter-index">{String(i+1).padStart(2,'0')}</div><div className="chapter-body"><div className="studio-section-label"><span>{r.blockKind||r.lane||'Brand context'}</span><RecordActions r={r} props={props} items={blocks}/></div><button className="chapter-title" onClick={()=>onOpen(r)}>{r.title}</button><p>{r.notes}</p>{r.assetUrl&&<MediaPreview url={r.assetUrl} mime={String(r.previewMime||r.mimeType||'')} label={r.title}/>}<small>{r.source||r.provenance||'Workspace note'} · {r.status}</small></div></DropTarget>)}</div></div>
}
const lenses:Record<string,{title:string;note:string;questions:string}>={Market:{title:'The category, and the gaps.',note:'Demand, pricing, the buying journey and whitespace.',questions:'What is changing? Where does TWH have permission to play?'},Audience:{title:'People before platforms.',note:'Needs, motivations, barriers, media habits and buying behaviour.',questions:'What do people need to believe before they choose TWH?'},Competitors:{title:'Find the meaningful difference.',note:'Positioning, communication, visual language and patterns.',questions:'What is everyone saying? What could TWH own?'},Trends:{title:'Signals worth paying attention to.',note:'Trends, cultural references and emerging behaviours.',questions:'Is this relevant to TWH, or simply popular?'},'Reference bank':{title:'Keep what sparks something.',note:'Hooks, reels, campaigns, art direction and cross-category ideas.',questions:'Save the source and the reason it matters.'}};
export function ResearchStudio(props:StudioProps){
 const [category,setCategory]=useState('Audience'),[query,setQuery]=useState(''),[sort,setSort]=useState('Manual order'),[lane,setLane]=useState('All audiences'),[evidence,setEvidence]=useState('All evidence');
 const all=props.records.filter(r=>r.section==='research'&&alive(r));let items=all.filter(r=>researchCategory(r)===category&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase())&&(lane==='All audiences'||r.lane===lane)&&(evidence==='All evidence'||r.evidence===evidence));
 items=[...items].sort(sort==='Name'?(a,b)=>a.title.localeCompare(b.title):sort==='Recently updated'?(a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')):sort==='Source'?(a,b)=>String(a.url||'').localeCompare(String(b.url||'')):manualOrder);
 const lens=lenses[category];return <div className="research-studio"><div className="studio-heading"><div><p className="eyebrow">TWH / RESEARCH</p><h1>Look closer.</h1></div>{props.canEdit&&<button className="button" onClick={()=>props.onOpen(fresh('research',{category,evidence:'Question',status:'Research needed'}))}><Plus size={15}/>{category==='Reference bank'?'Save a reference':'Add '+(category==='Competitors'?'competitor':'observation')}</button>}</div>
 <Tabs value={category} onValueChange={v=>{setCategory(v);setQuery('')}}><TabsList className="research-tabs">{researchCategories.map(c=><TabsTrigger key={c} value={c}>{c==='Audience'?'Target audience':c==='Market'?'Market research':c} <span>{all.filter(r=>researchCategory(r)===c).length}</span></TabsTrigger>)}</TabsList></Tabs>
 <div className="research-lens"><BookOpen size={28}/><div><h2>{lens.title}</h2><p>{lens.note}</p></div><small>{lens.questions}</small></div>
 <div className="studio-filters"><SectionSearch value={query} onChange={setQuery} placeholder="Search this research…"/><Picker label="Research audience" value={lane} onChange={setLane} options={['All audiences','Retail','Bespoke','Trade','Both']}/><Picker label="Research evidence" value={evidence} onChange={setEvidence} options={['All evidence','Question','Hypothesis','Client brief','Observed','Verified']}/><Picker label="Sort research" value={sort} onChange={setSort} options={['Manual order','Name','Recently updated','Source']}/></div>
 {category==='Reference bank'?<div className="reference-gallery">{items.map(r=><DropTarget key={r.id} r={r} props={props} className="reference-tile"><MediaPreview url={r.assetUrl||r.url} mime={String(r.previewMime||r.mimeType||'')} label={r.title}/><div className="reference-caption"><div className="studio-section-label"><small>{r.tags||'Saved reference'}</small><RecordActions r={r} props={props} items={items}/></div><button className="entry-title" onClick={()=>props.onOpen(r)}>{r.title}</button><p>{r.implication||r.notes}</p></div></DropTarget>)}</div>:<div className="research-notebook">{items.map((r,i)=><DropTarget r={r} props={props} key={r.id} className="research-entry"><div className="research-entry-head"><span className="entry-number">{String(i+1).padStart(2,'0')}</span><div><button className="entry-title" onClick={()=>props.onOpen(r)}>{r.title}</button><small>{r.evidence||'Research needed'}{r.lane?' · '+r.lane:''}{r.date?' · '+r.date:''}</small></div><RecordActions r={r} props={props} items={items}/></div><div className="insight-columns"><div><span>OBSERVATION</span><p>{r.notes||r.overview||'Add the observation, question or evidence.'}</p></div><div><span>INTERPRETATION</span><p>{r.insight||r.works||'What does this tell us?'}</p></div><div><span>FOR TWH</span><p>{r.implication||r.gaps||'What should this change in our thinking?'}</p></div></div>{r.url&&<a className="research-source" href={String(r.url)} target="_blank" rel="noreferrer"><Link2 size={13}/>Source / reference <ExternalLink size={12}/></a>}{r.assetUrl&&<MediaPreview url={r.assetUrl} mime={String(r.previewMime||r.mimeType||'')} label={r.title} compact/>}</DropTarget>)}</div>}
 {!items.length&&<div className="studio-empty"><h2>{category==='Trends'?'The next useful signal starts here.':'Nothing in this view yet.'}</h2><p>{category==='Trends'?'Save a trend with its source, date and relevance to TWH. Popularity alone is not an insight.':'Add a source or an observation, or clear your filters.'}</p>{props.canEdit&&<button className="text-button" onClick={()=>props.onOpen(fresh('research',{category,evidence:'Question'}))}>Add the first one <Plus size={15}/></button>}</div>}</div>
}
export function AssetStudio(props:StudioProps){
 const [query,setQuery]=useState(''),[type,setType]=useState('All types'),[collection,setCollection]=useState('All collections'),[campaign,setCampaign]=useState('All campaigns'),[sort,setSort]=useState('Manual order'),[busy,setBusy]=useState(''),[over,setOver]=useState(false);const input=useRef<HTMLInputElement>(null);
 const all=props.records.filter(r=>alive(r)&&(r.section==='asset'||r.section==='content'&&(r.assetUrl||r.liveUrl)));const collections=[...new Set(all.map(r=>String(r.collection||'')).filter(Boolean))];
 let items=all.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())&&(type==='All types'||r.format===type)&&(collection==='All collections'||r.collection===collection)&&(campaign==='All campaigns'||r.campaign===campaign));items=items.sort(sort==='Name'?(a,b)=>a.title.localeCompare(b.title):sort==='Recently added'?(a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')):manualOrder);
 async function upload(files:FileList|null){if(!files||!props.canEdit)return;for(const file of Array.from(files)){setBusy(file.name);try{const r=await uploadFile(file);props.onAccept(r);toast.success(file.name+' uploaded')}catch(e){toast.error((e as Error).message)}}setBusy('')}
 return <div className="asset-studio"><div className="studio-heading"><div><p className="eyebrow">TWH / ASSETS</p><h1>The work, in view.</h1></div>{props.canEdit&&<div className="studio-actions"><button className="button" onClick={()=>props.onOpen(fresh('asset',{format:'Video',status:'In progress'}))}><Link2 size={15}/>Add a link</button><button className="button primary" disabled={!!busy} onClick={()=>input.current?.click()}><Upload size={15}/>{busy?'Uploading…':'Upload files'}</button></div>}</div>
 <input ref={input} type="file" multiple hidden accept="image/png,image/jpeg,image/gif,image/webp,video/mp4,video/webm,application/pdf,font/woff2,.woff2" onChange={e=>{void upload(e.target.files);e.target.value=''}}/>
 <div className="studio-filters"><SectionSearch value={query} onChange={setQuery} placeholder="Search assets, tags, owners…"/><Picker label="Asset type" value={type} onChange={setType} options={['All types',...new Set(all.map(r=>String(r.format||'')).filter(Boolean))]}/><Picker label="Collection" value={collection} onChange={setCollection} options={['All collections',...collections]}/><Picker label="Asset campaign" value={campaign} onChange={setCampaign} options={['All campaigns',...new Set(all.map(r=>String(r.campaign||'')).filter(Boolean))]}/><Picker label="Sort assets" value={sort} onChange={setSort} options={['Manual order','Name','Recently added']}/></div>
 <div className={'asset-drop-area '+(over?'drop-over':'')} onDragOver={e=>{if(props.canEdit&&e.dataTransfer.types.includes('Files')){e.preventDefault();setOver(true)}}} onDragLeave={()=>setOver(false)} onDrop={e=>{e.preventDefault();setOver(false);void upload(e.dataTransfer.files)}}>
 {items.length?<div className="asset-gallery">{items.map(r=><DropTarget r={r} props={props} key={r.id} className="asset-tile"><MediaPreview url={r.assetUrl||r.liveUrl} mime={String(r.previewMime||r.mimeType||'')} label={r.title}/><div className="asset-caption"><div className="studio-section-label"><small>{r.format||'Creative'} · {r.status}</small><RecordActions r={r} props={props} items={items}/></div><button className="entry-title" onClick={()=>props.onOpen(r)}>{r.title}</button><small>{r.collection||r.owner||'Unsorted'}{r.versionLabel?' · '+r.versionLabel:''}</small></div></DropTarget>)}</div>:<div className="upload-empty"><ImageIcon size={44}/><h2>Make room for the actual work.</h2><p>Drop your images, videos or PDFs here.<br/>Or paste a video link and watch it in the workspace.</p>{props.canEdit&&<button className="text-button" onClick={()=>input.current?.click()}>Choose files <ArrowRight size={16}/></button>}</div>}
 </div><p className="media-help">Uploads up to 25 MB each. Add larger videos by YouTube, Vimeo or Google Drive link. Public Instagram posts and reels can also be embedded; playback follows the source’s sharing settings.</p>{busy&&<p className="upload-progress" role="status">Uploading {busy}…</p>}</div>
}
