'use client';
import { useEffect,useState } from 'react';
import { toast } from 'sonner';
import { MoreHorizontal,GripVertical,Pencil,Copy,Archive,Trash2,ArrowUp,ArrowDown,ExternalLink,Play,Image as ImageIcon,FileText,Search } from 'lucide-react';
import { DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator } from '@/components/ui/dropdown-menu';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import type { Entry } from './data';
import { mediaFor,safeMediaUrl } from './media';
export type StudioProps={accountLead?:string;records:Entry[];canEdit:boolean;onOpen:(r:Entry)=>void;onSave:(r:Entry)=>Promise<Entry>;onAccept:(r:Entry)=>void;onRemove:(r:Entry)=>void;onDuplicate:(r:Entry)=>void;onReorder:(id:string,before:string)=>void};
export const alive=(r:Entry)=>!['Archived','Deleted'].includes(r.status);
export const manualOrder=(a:Entry,b:Entry)=>Number(a.order||0)-Number(b.order||0);
export function Picker({value,onChange,options,label,labels={},disabled=false}:{value:string;onChange:(v:string)=>void;options:string[];label:string;labels?:Record<string,string>;disabled?:boolean}){return <Select disabled={disabled} value={value||'__none'} onValueChange={v=>onChange(v==='__none'?'':v)}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="__none">Not set</SelectItem>{options.map(x=><SelectItem key={x} value={x}>{labels[x]||x}</SelectItem>)}</SelectContent></Select>}
export function RecordActions({r,props,items=[]}:{r:Entry;props:StudioProps;items?:Entry[]}){if(!props.canEdit)return null;const i=items.findIndex(x=>x.id===r.id);return <div className="record-tools"><button draggable className="drag-handle" aria-label={'Reorder '+r.title} onDragStart={e=>{e.dataTransfer.setData('application/x-twh-record',r.id);e.dataTransfer.effectAllowed='move'}}><GripVertical size={16}/></button><DropdownMenu><DropdownMenuTrigger className="icon-button" aria-label={'Actions for '+r.title}><MoreHorizontal size={18}/></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>props.onOpen(r)}><Pencil size={15}/>Edit</DropdownMenuItem><DropdownMenuItem onClick={()=>props.onDuplicate(r)}><Copy size={15}/>Duplicate</DropdownMenuItem>{i>0&&<DropdownMenuItem onClick={()=>props.onReorder(r.id,items[i-1].id)}><ArrowUp size={15}/>Move up</DropdownMenuItem>}{i>=0&&i<items.length-1&&<DropdownMenuItem onClick={()=>props.onReorder(items[i+1].id,r.id)}><ArrowDown size={15}/>Move down</DropdownMenuItem>}<DropdownMenuSeparator/><DropdownMenuItem onClick={()=>void props.onSave({...r,status:'Archived',previousStatus:r.status}).catch(e=>toast.error(e.message))}><Archive size={15}/>Archive</DropdownMenuItem><DropdownMenuItem onClick={()=>props.onRemove(r)}><Trash2 size={15}/>Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>}
export function DropTarget({r,props,children,className=''}:{r:Entry;props:StudioProps;children:React.ReactNode;className?:string}){const [over,setOver]=useState(false);return <article className={className+(over?' drop-over':'')} onDragOver={e=>{if(props.canEdit&&e.dataTransfer.types.includes('application/x-twh-record')){e.preventDefault();setOver(true)}}} onDragLeave={()=>setOver(false)} onDrop={e=>{e.preventDefault();setOver(false);const id=e.dataTransfer.getData('application/x-twh-record');if(id&&id!==r.id)props.onReorder(id,r.id)}}>{children}</article>}
export function MediaPreview({url,mime='',label='Media preview',compact=false}:{url:unknown;mime?:string;label?:string;compact?:boolean}){
 const media=mediaFor(url,mime),[playing,setPlaying]=useState(false),[failed,setFailed]=useState(false);useEffect(()=>{setPlaying(false);setFailed(false)},[url]);
 const original=safeMediaUrl(url);return <div className={'media-preview '+(compact?'compact':'')}>
 {media.kind==='image'&&!failed?<img src={media.src} alt={label} loading="lazy" onError={()=>setFailed(true)}/>:media.kind==='video'&&!failed?<video controls preload="metadata" src={media.src} aria-label={label} onError={()=>setFailed(true)}/>:((media.kind==='iframe'||mime==='application/pdf')&&playing)?<iframe src={media.src} title={label} loading="lazy" allow="fullscreen; picture-in-picture; encrypted-media" allowFullScreen sandbox="allow-scripts allow-same-origin allow-presentation" referrerPolicy="strict-origin-when-cross-origin"/>:<div className="media-placeholder">{media.kind==='iframe'||media.kind==='video'?<Play size={28}/>:mime==='application/pdf'?<FileText size={28}/>:media.kind==='image'?<ImageIcon size={28}/>:<FileText size={28}/>}<span>{failed?'Preview unavailable':media.provider}</span>{(media.kind==='iframe'||mime==='application/pdf')&&!failed&&<button className="text-button" onClick={()=>setPlaying(true)}>{mime==='application/pdf'?'Read here':'Play here'}</button>}{original&&<a href={original} target="_blank" rel="noreferrer" className="text-button">Open source <ExternalLink size={13}/></a>}</div>}
 {(media.kind==='iframe'||mime==='application/pdf')&&playing&&<a className="embed-fallback" href={original} target="_blank" rel="noreferrer">If the source limits embedding, open it here <ExternalLink size={12}/></a>}
 </div>
}
export function SectionSearch({value,onChange,placeholder='Search…'}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <div className="search"><Search size={16}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></div>}
export async function uploadFile(file:File){if(file.size>25*1024*1024)throw new Error('Keep each file under 25 MB, or add a video / Drive link.');const res=await fetch('/api/uploads',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Name':encodeURIComponent(file.name)},body:file});const d=await res.json() as {record:Entry;error?:string};if(!res.ok)throw new Error(d.error||'Upload did not finish. Please try again.');return d.record;}
