'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { Activity,Fingerprint,Telescope,Route,Rocket,CalendarDays,Clapperboard,Images,Users,Wallet,ClipboardCheck,FolderOpen,BarChart3,LockKeyhole,Link2,Search,RefreshCw,ArrowUpRight,Plus } from 'lucide-react';
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarGroup,SidebarGroupLabel,SidebarGroupContent,SidebarInset,SidebarTrigger,useSidebar } from '@/components/ui/sidebar';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { CommandDialog,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem } from '@/components/ui/command';
import { Checkbox } from '@/components/ui/checkbox';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { type Entry } from './data';
import { BrandStudio,ResearchStudio,AssetStudio } from './studio';
import { type StudioProps,alive } from './studio-ui';
import { OperationalCalendar,type CalendarState } from './operational-calendar';
import { RecordEditor,type Activity as ActivityItem } from './editor';
import { Pulse,StrategyView,CampaignView,ScopeView,DirectoryView,LibraryView,InternalView } from './account-views';
import { Integrations } from './integrations';
import { eventsFor,affectedEvents } from './calendar';
const groups=[{label:'THE ACCOUNT',items:[['Pulse',Activity],['Account Calendar',CalendarDays]]},{label:'DIRECTION',items:[['Brand Guidelines',Fingerprint],['Research',Telescope],['Strategy',Route]]},{label:'THE WORK',items:[['Campaigns & Launches',Rocket],['Content Calendar',CalendarDays],['Creative & Production',Clapperboard],['Assets',Images]]},{label:'TOGETHER',items:[['Team & Partners',Users],['Scope',Wallet],['Decisions',ClipboardCheck],['Files',FolderOpen],['Reporting',BarChart3]]},{label:'AGENCY',items:[['Internal Management',LockKeyhole],['Integrations',Link2]]}] as const;
const pageSections:Record<string,string[]>={'Pulse':['task'],'Account Calendar':['event','content','production','campaign','strategy'],'Brand Guidelines':['brand','brandkit'],'Research':['research'],'Strategy':['strategy'],'Campaigns & Launches':['campaign','launch'],'Content Calendar':['content'],'Creative & Production':['production'],'Assets':['asset'],'Team & Partners':['team','vendor'],'Scope':['service'],'Decisions':['decision'],'Files':['file'],'Reporting':['report'],'Internal Management':['budget','private'],'Integrations':[]};
const aliases:Record<string,string>={'Overview':'Pulse','Brand & Business':'Brand Guidelines','Production':'Creative & Production','Team & Vendors':'Team & Partners','Scope & Budget':'Scope','Private Planning':'Internal Management','Launch':'Campaigns & Launches'};
function Navigation({active,go,allowed}:{active:string;go:(s:string)=>void;allowed:(s:string)=>boolean}){const {setOpenMobile}=useSidebar();return <>{groups.filter(g=>g.items.some(([n])=>allowed(n))).map(g=><SidebarGroup key={g.label}><SidebarGroupLabel>{g.label}</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{g.items.filter(([n])=>allowed(n)).map(([name,Icon])=><SidebarMenuItem key={name}><SidebarMenuButton isActive={active===name} onClick={()=>{go(name);setOpenMobile(false)}}><Icon/><span>{name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup>)}</>}
type Access={role:'admin'|'agency'|'client';name:string;email:string;areas:string[]};
type MoveRequest={entry:Entry;affected:ReturnType<typeof affectedEvents>;resolve:(r:Entry)=>void;reject:(e:Error)=>void};
export default function Dashboard(){
 const [accountLead,setAccountLead]=useState('Simran');
 const [records,setRecords]=useState<Entry[]>([]),[active,setActive]=useState('Pulse'),[access,setAccess]=useState<Access>({role:'client',name:'',email:'',areas:[]}),[ready,setReady]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[draft,setDraft]=useState<Entry|null>(null),[search,setSearch]=useState(false),[remove,setRemove]=useState<Entry|null>(null),[removeExternal,setRemoveExternal]=useState(false),[move,setMove]=useState<MoveRequest|null>(null),[selected,setSelected]=useState<string[]>([]),[moving,setMoving]=useState(false),[activity,setActivity]=useState<ActivityItem[]>([]),[calendar,setCalendar]=useState<CalendarState>({configured:false,connected:false,links:[]});const recordsRef=useRef(records);recordsRef.current=records;
 const accept=useCallback((r:Entry)=>setRecords(prev=>prev.some(x=>x.id===r.id)?prev.map(x=>x.id===r.id?r:x):[...prev,r]),[]);
 const refreshExtras=useCallback(async()=>{const results=await Promise.allSettled([fetch('/api/activity').then(r=>r.json() as Promise<{activity:ActivityItem[]}>),fetch('/api/calendar').then(r=>r.json() as Promise<CalendarState&{error?:string}>),fetch('/api/settings?key=account').then(r=>r.json() as Promise<{value?:{leadName:string}}>)]);if(results[0].status==='fulfilled')setActivity(results[0].value.activity||[]);if(results[1].status==='fulfilled'&&!results[1].value.error)setCalendar(results[1].value);if(results[2].status==='fulfilled'&&results[2].value.value)setAccountLead(results[2].value.value.leadName);},[]);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/records',{cache:'no-store'});const d=await r.json() as {records:Entry[];access:Access;error?:string};if(!r.ok)throw new Error(d.error);setRecords(d.records);setAccess(d.access);setReady(true);setError('');await refreshExtras();}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[refreshExtras]);
 const go=useCallback((name:string)=>{const next=aliases[name]||name;setActive(next);history.replaceState(null,'','#'+encodeURIComponent(next));window.scrollTo({top:0});},[]);
 useEffect(()=>{void load();const readHash=()=>{const h=decodeURIComponent(location.hash.slice(1));setActive(aliases[h]|| (h in pageSections?h:'Pulse'));};readHash();window.addEventListener('hashchange',readHash);const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(v=>!v)}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('hashchange',readHash);window.removeEventListener('keydown',key)};},[load]);
 useEffect(()=>{if(!ready)return;const id=new URL(location.href).searchParams.get('record');if(id){const r=records.find(r=>r.id===id);if(r){setDraft(r);history.replaceState(null,'',location.pathname+location.hash);}}},[ready,records]);
 useEffect(()=>{if(!calendar.connected||access.role==='client')return;const timer=setInterval(()=>{if(document.visibilityState==='visible')fetch('/api/calendar',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>r.ok?r.json() as Promise<{records:Entry[]}>:null).then(d=>{if(d?.records)setRecords(d.records);void refreshExtras()}).catch(()=>{});},60000);return()=>clearInterval(timer)},[calendar.connected,access.role,refreshExtras]);
 useEffect(()=>{if(!ready)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')fetch('/api/records',{cache:'no-store'}).then(r=>r.ok?r.json() as Promise<{records:Entry[];access:Access}>:null).then(d=>{if(d){setRecords(old=>JSON.stringify(old)===JSON.stringify(d.records)?old:d.records);setAccess(d.access);void refreshExtras();}}).catch(()=>{});},20000);return()=>clearInterval(timer)},[ready,refreshExtras]);
 const allowed=(name:string)=>name==='Pulse'||(access.role==='admin')||(name!=='Integrations'&&!(access.role==='client'&&name==='Internal Management')&&pageSections[name]?.some(s=>access.areas.includes(s)||access.areas.includes('*')));
 const open=useCallback((r:Entry)=>setDraft({...r}),[]);
 async function commit(r:Entry){const res=await fetch('/api/records',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});const data=await res.json() as {record:Entry;error?:string};if(!res.ok)throw new Error(data.error||'Could not save');accept(data.record);void refreshExtras();return data.record as Entry;}
 async function save(r:Entry):Promise<Entry>{const original=recordsRef.current.find(x=>x.id===r.id);if(original){const changed=eventsFor([original]).filter(e=>r[e.field]&&r[e.field]!==original[e.field]);const impacts=changed.flatMap(e=>affectedEvents(e,String(r[e.field]),recordsRef.current)).filter(e=>e.recordId!==r.id||r[e.field]===original[e.field]);const unique=[...new Map(impacts.map(e=>[e.id,e])).values()];if(unique.length){setSelected([]);return new Promise((resolve,reject)=>setMove({entry:r,affected:unique,resolve,reject}));}}return commit(r);}
 async function applyMove(){if(!move)return;setMoving(true);try{const saved=await commit(move.entry);const updates=new Map<string,Entry>([[saved.id,saved]]);for(const e of move.affected.filter(e=>selected.includes(e.id))){const latest=updates.get(e.recordId)||recordsRef.current.find(r=>r.id===e.recordId)||e.record;updates.set(e.recordId,{...latest,[e.field]:e.proposedDate});}for(const [id,r] of updates){if(id!==saved.id||JSON.stringify(r)!==JSON.stringify(saved))updates.set(id,await commit(r));}move.resolve(updates.get(saved.id)||saved);setMove(null);toast.success('Dates updated across the workspace')}catch(e){move.reject(e as Error);setMove(null);toast.error('Some changes may have saved. Refresh before retrying. '+(e as Error).message);void load()}finally{setMoving(false)}}
 function cancelMove(){if(moving)return;move?.reject(new Error('Date change cancelled.'));setMove(null);}
 async function reorder(id:string,before:string){const r=recordsRef.current.find(x=>x.id===id),target=recordsRef.current.find(x=>x.id===before);if(!r||!target||r.section!==target.section)return;const items=recordsRef.current.filter(x=>x.section===r.section&&alive(x)).sort((a,b)=>Number(a.order||0)-Number(b.order||0)).filter(x=>x.id!==id);items.splice(items.findIndex(x=>x.id===before),0,r);try{for(let i=0;i<items.length;i++)if(items[i].order!==i+1)await commit({...items[i],order:i+1});}catch(e){toast.error((e as Error).message);void load();}}
 const props:StudioProps={accountLead,records,canEdit:ready&&access.role!=='client',onOpen:open,onSave:save,onAccept:accept,onRemove:r=>{setRemoveExternal(false);setRemove(r)},onDuplicate:r=>{const copy:Entry={...r,id:crypto.randomUUID(),title:r.title+' · copy',version:0,status:'Proposed'};for(const k of ['createdAt','updatedAt','storageKey','fileName','fileSize','mimeType','privateOwner'])delete copy[k];setDraft(copy)},onReorder:(id,before)=>void reorder(id,before)};
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>void}}).modelContext;if(!context)return;const controller=new AbortController();try{context.registerTool({name:'read_twh_records',title:'Read saved TWH workspace records',description:'Read currently visible saved records. Permission-filtered. Does not change data.',inputSchema:{type:'object',properties:{section:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:{section?:string})=>({ready,records:records.filter(r=>!input.section||r.section===input.section)})},{signal:controller.signal});context.registerTool({name:'open_twh_record',title:'Open a TWH record',description:'Open the visible details of an existing record; does not save or approve.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:{id:string})=>{if(draft)throw new Error('Close the current editor first');const r=records.find(r=>r.id===input.id);if(!r)throw new Error('Record not found');open(r);return {opened:r.id}}},{signal:controller.signal});}catch{}return()=>controller.abort();},[records,ready,draft,open]);
 let content:React.ReactNode;if(!ready)content=<div className="workspace-loading">{loading?'Opening the account…':'The workspace could not be loaded.'}</div>;else if(!allowed(active))content=<div className="quiet-editorial"><h2>This area has not been shared with you.</h2><button className="text-button" onClick={()=>go('Pulse')}>Return to Pulse</button></div>;else switch(active){
 case 'Pulse':content=<Pulse props={props} activity={activity} go={go}/>;break;
 case 'Brand Guidelines':content=<BrandStudio {...props}/>;break;
 case 'Research':content=<ResearchStudio {...props}/>;break;
 case 'Strategy':content=<StrategyView props={props}/>;break;
 case 'Campaigns & Launches':content=<CampaignView props={props}/>;break;
 case 'Content Calendar':content=<OperationalCalendar key="content" props={props} context="content" calendar={calendar}/>;break;
 case 'Creative & Production':content=<OperationalCalendar key="production" props={props} context="production" calendar={calendar}/>;break;
 case 'Account Calendar':content=<OperationalCalendar key="account" props={props} context="account" calendar={calendar}/>;break;
 case 'Assets':content=<AssetStudio {...props}/>;break;
 case 'Team & Partners':content=<DirectoryView props={props}/>;break;
 case 'Scope':content=<ScopeView props={props}/>;break;
 case 'Decisions':content=<LibraryView props={props} section="decision"/>;break;
 case 'Files':content=<LibraryView props={props} section="file"/>;break;
 case 'Reporting':content=<LibraryView props={props} section="report"/>;break;
 case 'Internal Management':content=<InternalView props={props}/>;break;
 case 'Integrations':content=<Integrations props={props} calendar={calendar} refresh={load}/>;break;
 }
 return <SidebarProvider><Sidebar><SidebarHeader><button className="wordmark" onClick={()=>go('Pulse')}>PLUTONIK<span>CREATIVE HOUSE</span></button><div className="account"><b>T</b><div><strong>TWH</strong><small>Account workspace</small></div><span className="account-orbit">◌</span></div></SidebarHeader><SidebarContent><Navigation active={active} go={go} allowed={allowed}/></SidebarContent><SidebarFooter><div className="identity"><b>{access.role==='client'?'T':'P'}</b><div>{access.role==='admin'?accountLead:access.name||'TWH'}<small>{access.role==='admin'?'Account lead':access.role==='agency'?'Agency workspace':'Client workspace'}</small></div></div></SidebarFooter></Sidebar><SidebarInset><header className="topbar"><div><SidebarTrigger/><span>TWH</span><span>/</span><strong>{active}</strong></div><div><button className="global-search-button" onClick={()=>setSearch(true)}><Search size={16}/><span>Search the account</span><kbd>⌘ K</kbd></button><button className="icon-button" disabled={loading} aria-label="Refresh workspace" onClick={()=>void load()}><RefreshCw size={16}/></button></div></header><main className="workspace">{error&&<div className="error-note" role="alert">{error}<button onClick={()=>void load()}>Retry</button></div>}{content}</main></SidebarInset>
 {draft&&<RecordEditor key={draft.id+'-'+draft.version} entry={draft} props={props} calendar={calendar} internal={active==='Internal Management'} onClose={()=>setDraft(null)}/>}
 <CommandDialog open={search} onOpenChange={setSearch} title="Search the account" description="Find work, people, assets, sources and decisions across your shared workspace."><CommandInput placeholder="Search the entire account…"/><CommandList><CommandEmpty>No matching work.</CommandEmpty>{Object.entries(pageSections).filter(([name])=>allowed(name)).map(([name,sections])=><CommandGroup heading={name} key={name}><CommandItem value={'Go to '+name} onSelect={()=>{go(name);setSearch(false)}}>Open {name}<ArrowUpRight size={14}/></CommandItem>{records.filter(r=>sections.includes(r.section)&&alive(r)&&(name!=='Account Calendar'||r.section==='event')).map(r=><CommandItem key={r.id} value={r.id+' '+JSON.stringify(r)} onSelect={()=>{go(name);open(r);setSearch(false)}}><div>{r.title}<small>{r.section} · {r.status}{r.owner?' · '+r.owner:''}</small></div></CommandItem>)}</CommandGroup>)}</CommandList></CommandDialog>
 <AlertDialog open={!!remove} onOpenChange={v=>!v&&setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove {remove?.title}?</AlertDialogTitle><AlertDialogDescription>The record will go to the workspace trash. Its history is kept, and you can restore it.</AlertDialogDescription></AlertDialogHeader>{remove&&calendar.links.some(l=>l.record_id===remove.id&&l.external_id)&&<label className="checkbox-line"><Checkbox checked={removeExternal} onCheckedChange={v=>setRemoveExternal(!!v)}/>Also remove the connected Google event</label>}<AlertDialogFooter><AlertDialogCancel>Keep it</AlertDialogCancel><AlertDialogAction onClick={async()=>{if(!remove)return;const r=remove;try{const saved=await commit({...r,status:'Deleted',previousStatus:r.status,calendarDelete:removeExternal?'remove':'keep'});toast('Moved to trash',{action:{label:'Undo',onClick:()=>{void commit({...saved,status:r.status}).catch(e=>toast.error(e.message))}}});setRemove(null);if(draft?.id===r.id)setDraft(null)}catch(e){toast.error((e as Error).message)}}}>Move to trash</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!move} onOpenChange={v=>!v&&cancelMove()}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>This move may affect {move?.affected.length} upcoming dates.</AlertDialogTitle><AlertDialogDescription>Choose which dependent dates should move. Unchecked dates stay where they are.</AlertDialogDescription></AlertDialogHeader><div className="dependency-list">{move?.affected.map(e=><label className="checkbox-line" key={e.id}><Checkbox checked={selected.includes(e.id)} disabled={moving} onCheckedChange={v=>setSelected(s=>v?[...s,e.id]:s.filter(id=>id!==e.id))}/><div><strong>{e.title} · {e.label}</strong><small>{e.date} → {e.proposedDate}</small></div></label>)}</div><AlertDialogFooter><AlertDialogCancel disabled={moving} onClick={cancelMove}>Cancel move</AlertDialogCancel><button className="button primary" disabled={moving} onClick={()=>void applyMove()}>{moving?'Updating…':selected.length?'Move selected dates':'Move this date only'}</button></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster position="bottom-right"/></SidebarProvider>
}
